### ISSUE TITLE
Contact Us

### ISSUE THREAD

**Issue by dreamingblackcat** [thingaha/thingaha.org#1]
- [x] Khine Zar Thwe for General cases and Donations 
- [x] U Yawatta for Donation and Student, School infos
- [x] Hnin Oo Wai Hlaing and () for donations and account 
- [x] ChanMyaeSanHlaing and Sis Min Maw for

**Comment by yeemon04** [comment]
I want to try :D

**Comment by khinezarthwe** [comment]
@yeemon04  Hi Mama! Please reference [this infos ](https://drive.google.com/drive/u/0/folders/1c2785vfO-wksUlsgvyYYwBfEloigmtxU) for **Contact Us** Page
